const data = {
    products: [
        {
            _id: '1',
            name: 'kadın pantolon',
            slug: 'kadın-pantolon',
            category: 'pants',
            image: "https://img-s3.onedio.com/id-630fe06ef824d4996a212625/rev-0/w-620/f-jpg/s-c3584bbf7129f541282d3ebb737fd01052628ba7.jpg" ,
            price: 57,
            stock: 10,
            brand: 'defacto',
            rating: 4.5,
            reviews: 123,
            description: 'krem bol paça kadın pantolon',
        },
        {
            _id: '2',
            name: 'erkek pantolon',
            slug: 'erkek-pantolon',
            category: 'pants',
            image: "https://i.pinimg.com/736x/0f/9e/ce/0f9ece3605c4b05bbefb97c697a03ff0.jpg" ,
            price: 65,
            stock: 10,
            brand: 'koton',
            rating: 3.5,
            reviews: 163,
            description: 'gri kot erkek pantolon',
        },
        {
            _id: '3',
            name: 'kadın gömlek',
            slug: 'kadın-gömlek',
            category: 'shirts',
            image: "http://www.chamakhbutik.com/Uploads/UrunResimleri/buyuk/haki-baglamali-gomlek-belden-baglamali-4c6d-9.jpg" ,
            price: 60,
            stock: 10,
            brand: 'defacto',
            rating: 3.8,
            reviews: 23,
            description: 'kadın yeşil gömlek',
        },
        {
            _id: '4',
            name: 'erkek oduncu gömlek',
            slug: 'erkek-oduncu-gömlek',
            category: 'shirts',
            image: "https://imgrosetta.mynet.com.tr/file/13964480/640xauto.jpg" ,
            price: 100,
            stock: 10,
            brand: 'mavi',
            rating: 4.5,
            reviews: 123,
            description: 'erkek yeşil kalın oduncu gömlek',
        },
        {
            _id: '5',
            name: 'erkek ayakkabı',
            slug: 'erkek-ayakkabi',
            category: 'shoes',
            image: "https://www.serenze.com/i/m/001/0011810_siyah-fume-power-erkek-gunuk-ayakkabi.jpeg" ,
            price: 80,
            stock: 10,
            brand: 'lc-waikiki',
            rating: 3.5,
            reviews: 123,
            description: 'siyah erkek ayakkabı',
        },
        {
            _id: '6',
            name: 'kadın converse ayakkabı',
            slug: 'kadın-ayakkabi',
            category: 'shirts',
            image: "https://fns.modanisa.com/r/pro2/2021/06/15/z-woggo-2250-gunluk-keten-kadin-spor-ayakkabi-siyah-8011170-1.JPG" ,
            price: 120,
            stock: 30,
            brand: 'converse',
            rating: 4.8,
            reviews: 323,
            description: 'kadın siyah converse ayakkabı',
        },
        {
            _id: '7',
            name: 'kadın kazak',
            slug: 'kadin-kazak',
            category: 'shirts',
            image: "https://i.pinimg.com/564x/ef/a2/03/efa203cd54e1d20ed5a0ab2b4fb48a45.jpg" ,
            price: 50,
            stock: 30,
            brand: 'collesione',
            rating: 4.8,
            reviews: 323,
            description: 'kadın kazak',
        },
        {
            _id: '8',
            name: 'kadın tşört',
            slug: 'kadın-tsort',
            category: 't-shirts',
            image: "https://st.myideasoft.com/idea/cs/58/myassets/products/705/107-00144-2091.jpg?revision=1643005633" ,
            price: 78,
            stock: 30,
            brand: 'addax',
            rating: 4.8,
            reviews: 323,
            description: 'kadın çizgili tşört',
        },
        {
            _id: '9',
            name: 'kadın mont',
            slug: 'kadın-mont',
            category: 'coats',
            image: "https://www.ersangiyim.com/UserFiles/ProductImages/0/29268/orj/kapusonlu-yarim-boy-mont-siyah-2335965.jpg" ,
            price: 90,
            stock: 30,
            brand: 'mavi',
            rating: 4.8,
            reviews: 323,
            description: 'kadın siyah şişme mont',
        },
        {
            _id: '10',
            name: 'erkek kazak',
            slug: 'erkek-kazak',
            category: 'shirts',
            image: "https://i.pinimg.com/originals/44/31/54/44315409a28f1e74cbf5df796d83e4cb.jpg" ,
            price: 70,
            stock: 20,
            brand: 'defacto',
            rating: 4.8,
            reviews: 323,
            description: 'erkek krem kazak ',
        },
        {
            _id: '11',
            name: 'erkek mont',
            slug: 'erkek-mont',
            category: 'shirts',
            image: "https://cdn-gant.akinon.net/products/2021/08/13/22734/30066fda-a3af-4aa0-8e8c-0a769a6fc9ab_size800x1000_quality100_cropCenter.jpg" ,
            price: 160,
            stock: 10,
            brand: 'mudo',
            rating: 3.8,
            reviews: 523,
            description: 'erkek lacivert şişme mont',
        },
        {
            _id: '12',
            name: 'kadın converse ayakkabı',
            slug: 'erkek-hirka',
            category: 'shirts',
            image: "https://i.pinimg.com/736x/16/10/30/1610305e82f3c6e3745d10d3da4ca5b6.jpg" ,
            price: 70,
            stock: 30,
            brand: 'koton',
            rating: 2.8,
            reviews: 323,
            description: 'erkek beyaz oversize tşört',
        },
    ],
}

export default data;